[package]
name = "baba_is_clone"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.4", features = ["derive"] }
macroquad = "0.3.24"
ron = "0.8.0"
serde = { version = "1.0.145", features = ["derive"] }
